name: Terraform CI/CD - Dev

on:
  push:
    branches:
      - main
    paths:
      - 'Environment/Dev/**'
  pull_request:
    branches:
      - main
    paths:
      - 'Environment/Dev/**'
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_WORKING_DIR: Environment/Dev

jobs:
  terraform:
    name: Terraform Plan & Apply (Dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.5"

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

       # Create Execution Plan
      - name: Terraform Plan
        run: terraform plan

      
      # Apply only runs automatically on push to main (i.e. after PR merge)
      - name: Terraform Apply
        run: terraform apply -auto-approve 
